# Generated by Django 5.1.15 on 2026-02-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "veg",
                    models.BooleanField(
                        default=True, help_text="Green dot = veg, Red dot = non-veg"
                    ),
                ),
                (
                    "price_half",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Half portion price (₹)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "price_full",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Full portion price (₹)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "price_regular",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Regular / single price (₹)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a square food photo (min 600×600 px)",
                        null=True,
                        upload_to="menu/",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Show on homepage featured section"
                    ),
                ),
                (
                    "needs_verification",
                    models.BooleanField(
                        default=False, help_text="Flag item for chef / admin review"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide item from the public menu",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "ordering": ["category__display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["featured"], name="menu_menuit_feature_8190ce_idx"
                    ),
                    models.Index(
                        fields=["is_available"], name="menu_menuit_is_avai_3a30d9_idx"
                    ),
                ],
            },
        ),
    ]
