# Generated by Django 5.1.15 on 2026-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="egg",
            field=models.BooleanField(
                default=False,
                help_text="Contains egg but no meat (e.g. egg curry, egg bhurji). Set veg=False when this is True.",
            ),
        ),
    ]
